# -*- coding: utf-8 -*-
"""生成 data/knowledge.js —— 将 docs/ACP高频知识点总结.md 打包为前端可加载的 JS 字符串。

用法:
    python scripts/build_knowledge.py

输出:
    data/knowledge.js  (window.KNOWLEDGE_MD = "<markdown 原文>")
"""
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = ROOT / "docs" / "ACP高频知识点总结.md"
OUT = ROOT / "data" / "knowledge.js"


def main() -> int:
    if not SRC.exists():
        print(f"[错误] 找不到源文档: {SRC}", file=sys.stderr)
        return 1

    md = SRC.read_text(encoding="utf-8")
    # json.dumps 生成合法 JS 字符串；额外转义 "</" 防止 "</script>" 破坏内联脚本
    payload = json.dumps(md, ensure_ascii=False).replace("</", "<\\/")

    js = (
        "/* ============================================================\n"
        "   AUTO-GENERATED by scripts/build_knowledge.py\n"
        "   Source: docs/ACP高频知识点总结.md\n"
        "   Regenerate with: python scripts/build_knowledge.py\n"
        "   ============================================================ */\n"
        "window.KNOWLEDGE_MD = " + payload + ";\n"
    )
    OUT.write_text(js, encoding="utf-8")
    print(f"OK  {SRC.name} ({len(md)} chars) -> {OUT.name} ({len(js)} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
